package medley

import (
	"bytes"
	"context"
	"math/big"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/pkg/errors"
)

// Adapted from https://ethereum.stackexchange.com/a/80766

// GetRevertReason returns the reason for a failed transaction.
func GetRevertReason(
	ctx context.Context,
	b ethereum.ContractCaller,
	from common.Address,
	tx *types.Transaction,
	blockNum *big.Int,
) error {
	msg := ethereum.CallMsg{
		From:     from,
		To:       tx.To(),
		Gas:      tx.Gas(),
		GasPrice: tx.GasPrice(),
		Value:    tx.Value(),
		Data:     tx.Data(),
	}
	res, err := b.CallContract(ctx, msg, blockNum)
	if err != nil {
		return err
	}
	// not sure if we ever call into unpackError. The call to CallContract already raises an
	// error with the reason.
	return unpackError(res)
}

var (
	errorSig     = []byte{0x08, 0xc3, 0x79, 0xa0} // Keccak256("Error(string)")[:4]
	abiString, _ = abi.NewType("string", "", nil)
)

func unpackError(result []byte) error {
	if len(result) < 4 || !bytes.Equal(result[:4], errorSig) {
		return errors.New("TX result not of type Error(string)")
	}
	vs, err := abi.Arguments{{Type: abiString}}.UnpackValues(result[4:])
	if err != nil {
		return errors.Wrap(err, "unpack revert reason")
	}
	return errors.Errorf("Error: %s", vs[0].(string))
}
